### ISSUE TITLE
[Endpoint] POST api/employee/:employeeId/remuneration

### ISSUE THREAD

**Issue by pawap90** [mauro-codes/uade-gym-api#38]
Method: `POST`

Route: `api/employee/:employeeId/remuneration`

More info:
- Creates a new document on the `remuneration` collection
- The `details` array contains the details of the paycheck
- Before creating the document, calculate the `total` by adding the value of each item in `details`.

Model: The model should be created to close this issue.
```yaml
- employeeId: reference - required
- date: date - required
- details: array  - required
  - description: string  - required
  - value: number  - required
- total: - number - required (calculated server-side)
```

Example body:
```json
{
    "employeeId": "1234",
    "date": "2020-07-14",
    "details": [
        {
            "description": "Gross monthly salary",
            "value": 2000
        },
        {
            "description": "Bonus",
            "value": 200
        },
        {
            "description": "Social security",
            "value": -200
        },
        {
            "description": "Taxes",
            "value": -300
        }
    ]
}
```
