### ISSUE TITLE
[Endpoint] POST api/plan

### ISSUE THREAD

**Issue by pawap90** [mauro-codes/uade-gym-api#42]
Method: `POST`

Route: `api/plan`

More info:
- Creates a new document on the `plan` collection

Model: The model should be created to close this issue.
```yaml
- name: string  - required
- frequency: string (enum)  - required
- price: number - required
```

- The `frecuency` is a string but can only have one of the following values:
  - daily
  - weekly
  - biweekly (every 2 weeks)
  - monthly
  - biannual (every 6 months)
  - yearly

The value provided on the body for `frecuency` must be validated and throw 400 (bad request) if it doesn't match the previously defined values.

Example body:
```json
{
    "name": "Pay for 6 months!",
    "frecuency": "biannual",
    "price": 199
}
```
