### ISSUE TITLE
[Endpoint] PUT api/member/:memberId/plan

### ISSUE THREAD

**Issue by pawap90** [mauro-codes/uade-gym-api#46]
Method: `PUT`

Route: `api/member/:memberId/plan`

Assigns a `plan` to the specified member

Update `member` schema to add the following property:
```yaml
- plan: (optional)
    - id: string (required)
    - date: Date (required - default = now)
```
Example body:
```json
{
    "planId": "123asd123"
}
```
