### ISSUE TITLE
[Endpoint] POST api/member/:memberId/payment

### ISSUE THREAD

**Issue by pawap90** [mauro-codes/uade-gym-api#47]
Method: `POST`

Route: `api/member/:memberId/payment`

Model: The model should be created to close this issue.
```yaml
- memberId: string - id referenced - required
- date: date - required - default = now
- expirationDate: date - required
- planId: string - id referenced - required
- value: number - required
```

This **endpoint has no body** because all of the values must be calculated server-side, except the `memberId` which is defined as a route param.

More info:
- Creates a new document on the `payment` collection
- Receives only the member id, and calculates the rest of the info extracting data from the member document and the plan document.
- The `planId` is the plan currently asigned to the specified member.
- The `date` is the current date.
- The `expirationDate` can be calculated by adding the plan's `frecuency` to the `date`
- The `value` is the `price` of the plan.
